#!/bin/env python


from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
# setup Lambert Conformal basemap.
# set resolution=None to skip processing of boundary datasets.
m = Basemap(width=12000000,height=9000000,projection='lcc',
            resolution=None,lat_1=48,lat_2=65,lat_0=50,lon_0=-107.)
m.etopo()
plt.show()


